BATTERIES = [
    {
        "id": 1,
        "name": "Megapack 2XL",
        "dimensions": {"length": 10, "width": 40, "unit": "ft"},
        "energy": 4,
        "energy_unit": "MWh",
        "cost": 120000,
        "cost_currency": "USD",
        "releaseDate": "2022-01-01",
        "weight": 40000,
        "weight_unit": "kg",
    },
    {
        "id": 2,
        "name": "Megapack 2",
        "dimensions": {"length": 10, "width": 30, "unit": "ft"},
        "energy": 3,
        "energy_unit": "MWh",
        "cost": 80000,
        "cost_currency": "USD",
        "releaseDate": "2021-03-15",
        "weight": 35000,
        "weight_unit": "kg",
    },
    {
        "id": 3,
        "name": "Megapack",
        "dimensions": {"length": 10, "width": 30, "unit": "ft"},
        "energy": 2,
        "energy_unit": "MWh",
        "cost": 50000,
        "cost_currency": "USD",
        "releaseDate": "2005-06-30",
        "weight": 30000,
        "weight_unit": "kg",
    },
    {
        "id": 4,
        "name": "Powerpack",
        "dimensions": {"length": 10, "width": 10, "unit": "ft"},
        "energy": 1,
        "energy_unit": "MWh",
        "cost": 20000,
        "cost_currency": "USD",
        "releaseDate": "2000-12-01",
        "weight": 15000,
        "weight_unit": "kg",
    },
]

TRANSFORMER = {
    "id": 1,
    "name": "Transformer",
    "dimensions": {"length": 10, "width": 10, "unit": "ft"},
    "energy": 4,
    "energy_unit": "MWh",
    "cost": 120000,
    "cost_currency": "USD",
    "releaseDate": "2022-05-20",
    "weight": 45000,
    "weight_unit": "kg",
}
